package com.rest.domain;
// Generated Feb 26, 2018 8:43:55 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name = "model", catalog = "ifAR")
public class Model implements java.io.Serializable {

	private Integer id;
	private SellerRequest sellerRequest;
	private int width;
	private int height;
	private int length;
	private String link;
	private int status;
	private Date createdAt;
	private Set<Product> products = new HashSet<Product>(0);

	public Model() {
	}

	public Model(SellerRequest sellerRequest, int width, int height, int length, String link, int status,
			Date createdAt) {
		this.sellerRequest = sellerRequest;
		this.width = width;
		this.height = height;
		this.length = length;
		this.link = link;
		this.status = status;
		this.createdAt = createdAt;
	}

	public Model(SellerRequest sellerRequest, int width, int height, int length, String link, int status,
			Date createdAt, Set<Product> products) {
		this.sellerRequest = sellerRequest;
		this.width = width;
		this.height = height;
		this.length = length;
		this.link = link;
		this.status = status;
		this.createdAt = createdAt;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seller_request_id", nullable = false)
	public SellerRequest getSellerRequest() {
		return this.sellerRequest;
	}

	public void setSellerRequest(SellerRequest sellerRequest) {
		this.sellerRequest = sellerRequest;
	}

	@Column(name = "width", nullable = false)
	public int getWidth() {
		return this.width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false)
	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	@Column(name = "length", nullable = false)
	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	@Column(name = "link", nullable = false, length = 250)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "model")
	@JsonBackReference
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
