package com.rest.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.rest.domain.OrderDetail;
import com.rest.domain.Role;
import com.rest.repository.OrderDetailRepository;
import com.rest.repository.RoleRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/IFAR") // This means URL's start with /demo (after
								// Application path)
public class RoleController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle
				// the data
	private RoleRepository roleRepository;
	private OrderDetailRepository orderRepository;

	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view
		// name
		// @RequestParam means it is a parameter from the GET or POST request

		Role n = new Role();
		n.setName(name);
		roleRepository.save(n);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<OrderDetail> getAllUsers() {
		// This returns a JSON or XML with the users
		System.out.println("dawdawdawdawdawd" + orderRepository.findAll().iterator().next().toString());
		return orderRepository.findAll();
	}
}
